document.writeln(" <div style=\'*z-index:11;*position:relative;width:100%;height:620px;margin-left:auto;margin-right:auto;background-color:\'>");
document.writeln("                <div class=\'header page_header yibuLayout_tempPanel\' style=\'width:1000px;height:620px;;\'>");
document.writeln("");
document.writeln("                    <div class=\'runTimeflowsmartView\'>");
document.writeln("                        <!-- logo -->");
document.writeln("                        <div  id=\'view_image_32_843\' class=\'yibuSmartViewMargin absPos\'   >");
document.writeln("                            <div class=\'yibuFrameContent overflow_hidden image_Style1_Item0\' style=\'height:48px;width:127px;\'>");
document.writeln("                                <div class=\'megwh\' style=\'height:100%; width:100%;\'>");
document.writeln("                                    <a id=\'autosize_view_image_32_843\' href=\'javascript:void(0)\' target=\'_self\' >");
document.writeln("                                        <input id=\'w_view_image_32_843\' type=\'hidden\' value=\'792\' />");
document.writeln("                                        <input id=\'h_view_image_32_843\' type=\'hidden\' value=\'295\' />");
document.writeln("                                        <input id=\'canadjustwidth_view_image_32_843\' type=\'hidden\' value=\'False\' />");
document.writeln("                                        <input id=\'canadjustheight_view_image_32_843\' type=\'hidden\' value=\'False\' />");
document.writeln("");
document.writeln("                                        <img class=\'lazyload\' src=\'./imgages/6894337_logo2_fb84d9a4-c176-4462-94ee-c77f5f758092_resize_picture.jpeg\' data-original=\'http://img1.bj.wezhan.cn/content/sitefiles/2017101/images/6894337_logo2_fb84d9a4-c176-4462-94ee-c77f5f758092_resize_picture.jpeg\' alt=\'\' style=\'border:none; position:relative;\' />");
document.writeln("                                    </a>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                        <div  id=\'view_photoalbum_33_843\' class=\'yibuSmartViewMargin absPos\'   >");
document.writeln("                            <div class=\'yibuFrameContent overflow_hidden photoalbum_Style2_Item0 view_photoalbum_33_843_Style2_Item0\' style=\'height:500px;width:1000px;\'>");
document.writeln("                                <div class=\'w_slider_2 renderfullScreen w_slider_2_33\'>");
document.writeln("                                    <!-- banner-img -->");
document.writeln("                                    <div class=\'w_slider_img\'>");
document.writeln("                                        <ul>");
document.writeln("                                            <li style=\'background: url(./images/6533764_1.jpeg) center 0 no-repeat;\'>");
document.writeln("                                                <div class=\'siteWidth\'>");
document.writeln("");
document.writeln("                                                    <p class=\'txt\'   style=\'display:none;\'       >");
document.writeln("                                                        1");
document.writeln("                                                        <span class=\'btn\'></span>");
document.writeln("                                                    </p>");
document.writeln("                                                    <p class=\'txtDesc\'   style=\'display: none;\'         >图片0</p>");
document.writeln("");
document.writeln("                                                    <a   style=\' cursor:default\'                                title=\'1\' href=\'javascript:void(0);\'></a>");
document.writeln("");
document.writeln("                                                </div>");
document.writeln("                                            </li>");
document.writeln("                                            <li style=\'background: url(./images/6533765_2.jpeg) center 0 no-repeat;\'>");
document.writeln("                                                <div class=\'siteWidth\'>");
document.writeln("");
document.writeln("                                                    <p class=\'txt\'   style=\'display:none;\'       >");
document.writeln("                                                        2");
document.writeln("                                                        <span class=\'btn\'></span>");
document.writeln("                                                    </p>");
document.writeln("                                                    <p class=\'txtDesc\'   style=\'display: none;\'         >图片1</p>");
document.writeln("");
document.writeln("                                                    <a   style=\' cursor:default\'                                title=\'2\' href=\'javascript:void(0);\'></a>");
document.writeln("");
document.writeln("                                                </div>");
document.writeln("                                            </li>");
document.writeln("                                            <li style=\'background: url(./images/6892817_首页01.jpeg) center 0 no-repeat;\'>");
document.writeln("                                                <div class=\'siteWidth\'>");
document.writeln("");
document.writeln("                                                    <p class=\'txt\'   style=\'display:none;\'       >");
document.writeln("                                                        首页01");
document.writeln("                                                        <span class=\'btn\'></span>");
document.writeln("                                                    </p>");
document.writeln("                                                    <p class=\'txtDesc\'   style=\'display: none;\'         >图片2</p>");
document.writeln("");
document.writeln("                                                    <a   style=\' cursor:default\'                                title=\'首页01\' href=\'javascript:void(0);\'></a>");
document.writeln("");
document.writeln("                                                </div>");
document.writeln("                                            </li>");
document.writeln("                                            <li style=\'background: url(./images/6892818_首页02.jpeg) center 0 no-repeat;\'>");
document.writeln("                                                <div class=\'siteWidth\'>");
document.writeln("");
document.writeln("                                                    <p class=\'txt\'   style=\'display:none;\'       >");
document.writeln("                                                        首页02");
document.writeln("                                                        <span class=\'btn\'></span>");
document.writeln("                                                    </p>");
document.writeln("                                                    <p class=\'txtDesc\'   style=\'display: none;\'         >图片3</p>");
document.writeln("");
document.writeln("                                                    <a   style=\' cursor:default\'                                title=\'首页02\' href=\'javascript:void(0);\'></a>");
document.writeln("");
document.writeln("                                                </div>");
document.writeln("                                            </li>");
document.writeln("                                        </ul>");
document.writeln("                                    </div>");
document.writeln("                                    <!-- 下面是前/后按钮代码，如果不需要删除即可 -->");
document.writeln("                                    <a  class=\'prev\' href=\'javascript:void(0)\'></a>");
document.writeln("                                    <a  class=\'next\' href=\'javascript:void(0)\'></a>");
document.writeln("");
document.writeln("                                    <div class=\'w_slider_num\'   style=\'display:none;\'      >");
document.writeln("                                        <ul></ul>");
document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("");
document.writeln("                                <script type=\'text/javascript\'>");
document.writeln("    $(document).ready(function () {");
document.writeln("        setRenderFullScreen($(\'#view_photoalbum_33_843\'));");
document.writeln("        $(\'.w_slider_2_33\').slide({");
document.writeln("            titCell: $(\'.w_slider_2_33 .w_slider_num ul\'),");
document.writeln("            mainCell: $(\'.w_slider_2_33 .w_slider_img ul\'),");
document.writeln("            effect: \'fade\',");
document.writeln("            autoPlay: \'true\',");
document.writeln("            autoPage: true,");
document.writeln("            trigger: \'click\',");
document.writeln("            interTime: \'3000\'");
document.writeln("        });");
document.writeln("    });");
document.writeln("</script>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                        <div  id=\'view_navigator_34_843\' class=\'yibuSmartViewMargin absPos\'   >");
document.writeln("");
document.writeln("                            <div class=\'yibuFrameContent overflow_hidden navigator_Style2_Item0 view_navigator_34_843_Style2_Item0\' style=\'height:100px;width:720px;\'>");
document.writeln("                                <ul id=\'nav_view_navigator_34_843 styleItem=Style2\'>");
document.writeln("                                    <li class=w_nav_item style=width:16.66%;*width:16.33%>");
document.writeln("                                        <h3>");
document.writeln("                                            <a href=\'index.html\' target=_self>首页</a>");
document.writeln("                                        </h3>");
document.writeln("                                    </li>");
document.writeln("                                    <li class=w_nav_item style=width:16.66%;*width:16.33%>");
document.writeln("                                        <h3>");
document.writeln("                                            <a href=\'gywm.html\' target=_self>关于我们</a>");
document.writeln("                                        </h3>");
document.writeln("                                    </li>");
document.writeln("                                    <li class=w_nav_item style=width:16.66%;*width:16.33%>");
document.writeln("                                        <h3>");
document.writeln("                                            <a href=\'xwzx.html\' target=_self>新闻资讯</a>");
document.writeln("                                        </h3>");
document.writeln("                                    </li>");
document.writeln("                                    <li class=w_nav_item style=width:16.66%;*width:16.33%>");
document.writeln("                                        <h3>");
document.writeln("                                            <a href=\'cpzs.html\' target=_self>产品展示</a>");
document.writeln("                                        </h3>");
document.writeln("                                    </li>");
document.writeln("                                    <li class=w_nav_item style=width:16.66%;*width:16.33%>");
document.writeln("                                        <h3>");
document.writeln("                                            <a href=\'rczp.html\' target=_self>人才招聘</a>");
document.writeln("                                        </h3>");
document.writeln("                                    </li>");
document.writeln("                                    <li class=w_nav_item style=width:16.66%;*width:16.33%>");
document.writeln("                                        <h3>");
document.writeln("                                            <a href=\'lxwm.html\' target=_self>联系我们</a>");
document.writeln("                                        </h3>");
document.writeln("                                    </li>");
document.writeln("                                </ul>");
document.writeln("");
document.writeln("                                <input type=\'hidden\' id=\'HeightVariablesStr_view_navigator_34_843\' value=\'$height:100px;$Item_height:100px;$SubItem_height:100px;\' />");
document.writeln("                                <script>");
document.writeln("    $(function () {");
document.writeln("        slideMenu(\'nav_\' + \'view_navigator_34_843\');");
document.writeln("        jQuery(\'#nav_\' + \'view_navigator_34_843\').parent(\'div\').css(\'overflow\', \'visible\');");
document.writeln("        var isDivider = true;");
document.writeln("");
document.writeln("        //子导航下边框显示不出来的fix");
document.writeln("        $(\'#nav_\' + \'view_navigator_34_843\').children(\'li\').each(function () {");
document.writeln("            var Li_height = $(this).height();");
document.writeln("            $(\'li\', this).height(Li_height);");
document.writeln("");
document.writeln("            var child_li = $(\'li\', this);");
document.writeln("            var topborderwidth = $(\'a:first\', child_li).css(\'border-top-width\');");
document.writeln("            topborderwidth = isNaN(parseInt(topborderwidth)) ? 0 : parseInt(topborderwidth);");
document.writeln("            var bottomborderwidth = $(\'a:first\', child_li).css(\'border-bottom-width\');");
document.writeln("            bottomborderwidth = isNaN(parseInt(bottomborderwidth)) ? 0 : parseInt(bottomborderwidth);");
document.writeln("            var aheight = Li_height - topborderwidth - bottomborderwidth;");
document.writeln("            $(\'a\', child_li).height(aheight);");
document.writeln("        });");
document.writeln("");
document.writeln("        jQuery(\'#nav_\' + \'view_navigator_34_843\').children(\'li\').each(function () {");
document.writeln("            var topWidth = $(this).children(\'h3\').children(\'a\').css(\'border-top-width\');");
document.writeln("            var leftWidth = $(this).children(\'h3\').children(\'a\').css(\'border-left-width\');");
document.writeln("            var bottomWidth = $(this).children(\'h3\').children(\'a\').css(\'border-bottom-width\');");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("            if (topWidth != \'0\' && topWidth != \'0px\') {");
document.writeln("                isDivider = false;");
document.writeln("                return false;");
document.writeln("            }");
document.writeln("            if (leftWidth != \'0\' && leftWidth != \'0px\') {");
document.writeln("                isDivider = false;");
document.writeln("                return false;");
document.writeln("            }");
document.writeln("            if (bottomWidth != \'0\' && bottomWidth != \'0px\') {");
document.writeln("                isDivider = false;");
document.writeln("                return false;");
document.writeln("            }");
document.writeln("");
document.writeln("");
document.writeln("            if ($(this).children(\'ul\').length > 0) {");
document.writeln("                var maxWidth = $(this).children(\'ul\').width();");
document.writeln("                $(this).children(\'ul\').children(\'li\').each(function () {");
document.writeln("");
document.writeln("                    var a = $(this).children(\'a\');");
document.writeln("                    var currentWidth = GetCurrentStrWidth(a.html(), a.css(\'font-size\')) + 20;");
document.writeln("                    if (maxWidth < currentWidth)");
document.writeln("                        maxWidth = currentWidth;");
document.writeln("                });");
document.writeln("                $(this).children(\'ul\').css(\'width\', maxWidth + \'px\');");
document.writeln("            }");
document.writeln("        });");
document.writeln("        //if (isDivider)");
document.writeln("        //    jQuery(\'#nav_\' + \'view_navigator_34_843\').children(\'li:last\').children(\'h3\').children(\'a\').css(\'border-right-width\', \'0px\');//去掉最后一项的分隔线");
document.writeln("");
document.writeln("        if (\'False\' == \'False\') {");
document.writeln("            jQuery(\'#\' + \'view_navigator_34_843\').css(\'z-index\', \'999999\');");
document.writeln("            if ($.browser.msie) {");
document.writeln("                jQuery(\'#\' + \'view_navigator_34_843\').parent(\'.runTimeflowsmartView\').css(\'z-index\', \'999999\');");
document.writeln("            }");
document.writeln("            if (jQuery(\'#\' + \'view_navigator_34_843\').parent().attr(\'class\') != \'runTimeflowsmartView\') {//导航可能放在容器控件中了，需要把容器控件的z-index的值设大");
document.writeln("                jQuery(\'#\' + \'view_navigator_34_843\').parent(\'.w_container_content\').parent().parent().css(\'z-index\', \'999998\');");
document.writeln("            }");
document.writeln("        }");
document.writeln("        SetNavSelectedStyle(\'nav_\' + \'view_navigator_34_843\', \'nav\');//选中当前导航");
document.writeln("    })");
document.writeln("</script>");